# Generated by Django 4.1.7 on 2023-03-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoregistrationKeith', '0004_student_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('price', models.IntegerField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('quantity', models.IntegerField(blank=True, max_length=50)),
            ],
        ),
    ]
